# Generated by Django 4.2 on 2023-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category2',
            options={'ordering': ('name',)},
        ),
    ]
