# Generated by Django 4.2 on 2023-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_category2_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',)},
        ),
    ]
