# Generated by Django 4.2 on 2023-04-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_items_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category2',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
