# Generated by Django 4.2 on 2023-04-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_category2_options_alter_items_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('name',), 'verbose_name_plural': 'Items'},
        ),
    ]
