# Generated by Django 4.2 on 2023-04-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='is_sold',
            new_name='sold',
        ),
    ]
