# Generated by Django 4.2 on 2023-05-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('user',), 'verbose_name_plural': 'Orders'},
        ),
    ]
