# Generated by Django 4.2 on 2023-05-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
