# Generated by Django 4.2 on 2023-05-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
