# Generated by Django 4.2 on 2023-05-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item1_quantity', models.PositiveIntegerField(default=0)),
                ('item2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item2_quantity', models.PositiveIntegerField(default=0)),
                ('item3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item3_quantity', models.PositiveIntegerField(default=0)),
                ('item4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item4_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item4_quantity', models.PositiveIntegerField(default=0)),
                ('item5_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item5_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item5_quantity', models.PositiveIntegerField(default=0)),
                ('item6_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item6_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item6_quantity', models.PositiveIntegerField(default=0)),
                ('item7_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item7_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item7_quantity', models.PositiveIntegerField(default=0)),
                ('item8_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item8_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item8_quantity', models.PositiveIntegerField(default=0)),
                ('item9_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item9_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item9_quantity', models.PositiveIntegerField(default=0)),
                ('item10_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item10_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item10_quantity', models.PositiveIntegerField(default=0)),
                ('item11_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item11_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item11_quantity', models.PositiveIntegerField(default=0)),
                ('item12_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item12_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item12_quantity', models.PositiveIntegerField(default=0)),
                ('item13_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item13_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item13_quantity', models.PositiveIntegerField(default=0)),
                ('item14_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item14_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item14_quantity', models.PositiveIntegerField(default=0)),
                ('item15_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item15_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item15_quantity', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
