# Generated by Django 4.2 on 2023-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_order_product_name_remove_order_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(),
        ),
    ]
