# Generated by Django 4.2 on 2023-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(default='items'),
        ),
    ]
