# Generated by Django 4.2 on 2023-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_mymodel_alter_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
