# Generated by Django 4.2 on 2023-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(default='items', max_length=1000),
        ),
    ]
