# Generated by Django 4.2 on 2023-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_remove_order_products_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='items ordered'),
        ),
    ]
