# Generated by Django 4.2 on 2023-05-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
