# Generated by Django 4.2 on 2023-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
